version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    volumes:
      - ./sql-dump-query:/docker-entrypoint-initdb.d